- hosts: all
  become: true
  tasks:

  - name: update repository index & install nginx package
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"